version: '3.9'

services:
  nodejs:
    image: node:latest
    working_dir: /app
    container_name: iktickets-nodejs
    volumes:
      - ./app:/app/
    command: tail -f /dev/null
    ports:
      - '5173:5173'